# Configure a default setup of Home Assistant (frontend, api, etc)
---

http:
    base_url: !secret http_url
    ssl_certificate: /ssl/fullchain.pem
    ssl_key: /ssl/privkey.pem

google_assistant:
    project_id: !secret g_assistant_id
    api_key: !secret g_assistant_api_key

# Text to speech
tts:
    - platform: google_translate
      service_name: google_say

media_player:
    - platform: samsungtv
      host: 192.168.1.3
      mac: !secret samsung_mac
      port: 8002
      timeout: 5
      name: Living room TV

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
